### ISSUE TITLE
Q: What was the motivation to create this library while having other libraries in OSS?

### ISSUE THREAD

**Issue by tim-fay** [ozontech/state-transition#1]
I'd like to understand what the motivation behind the creation of this utility library was.
For example, there's a well-known and mature Stateless (https://github.com/dotnet-state-machine/stateless) originally created by Nicholas Blumhardt who stands behind Serilog, Autofac and few other famous OS libraries. API is pretty much looks similar. 

- Have you tried the one mentioned above?
- What was the reason that drove the team to create its own solution?
- Would be nice to add performance comparison in the benchmarks you've provided.

Thanks!

**Comment by dbeylkhanov** [comment]
Hey Tim,
 I would recommend you to look first at the according sections([motivation](https://github.com/ozontech/state-transition?tab=readme-ov-file#motivation), [features](https://github.com/ozontech/state-transition?tab=readme-ov-file#main-features), [performance](https://github.com/ozontech/state-transition?tab=readme-ov-file#performance) ) of the readme 

**UPD**
Added more details about performance

Thanks
